### ISSUE TITLE
Example implementation

### ISSUE THREAD

**Issue by challme28** [riyase/RealmCookieJar#1]
I'm using this gist for my cookies https://gist.github.com/tsuharesu/cbfd8f02d46498b01f1b and I wanted to avoid the use of `Context `through Realm but I'm failing to implement this code there since I'm not sure how to use your git and this function `saveFromResponse(HttpUrl url, List<Cookie> cookies)` since on the gist I get the cookies as `String` and not as `Cookie` objects.
Thanks

**Comment by riyase** [comment]
actually i did this because i wanted to store cookies in [realm](https://realm.io/docs/java/latest/) db. and i am using okhttp3 as client..
eg:
`RealmCookieJar realmCookieJar = new RealmCookieJar(realmConfiguration);
//realmCookieJar.hostAsKey(true);
OkHttpClient.Builder builder = new OkHttpClient.Builder();
builder.cookieJar(realmCookieJar);
`

**Comment by challme28** [comment]
Cool, now I want to add a cookie as I used to do with the gist
`Request.Builder builder = chain.request().newBuilder(); `
`HashSet<String> preferences=(HashSet<String>) pref.getStringSet("pref_cookies",new HashSet<String>());`
`builder.addHeader("device","mobile");`

I tried adding them on `saveFromResponse` and `loadForRequest` but server won't read catch it.

**Comment by riyase** [comment]
Are you using okhttp3 as client?

**Comment by challme28** [comment]
Yes

**Comment by riyase** [comment]
I assume you shared code from intercept methode. U dont need to add cookies manually to each request.. you can use okhttp3 builder's cookiejar method for that by passing your cookiejar implementation. Okttp3 will use savefromResponse & loadforRequest internally if u set a cookiejar

**Comment by riyase** [comment]
Here is one cookiejar implementation using sharedPreferences [link](https://github.com/franmontiel/PersistentCookieJar)

**Comment by challme28** [comment]
I'm already using an implementation that uses SharedPreferences and allows me to put the cookie I want to each request with  `OkHtttpClient.Builder.addIntecerptor`
I'm now looking to use Realm instead of SharedPreferences. And for this I'd like to put a cookie for each request on you Realm implementation with name: device and value: mobile

**Comment by riyase** [comment]
You can access RealmCookieJar using the following code
`RealmCookieJar realmCookieJar = (RealmCookieJar)okHttpClient.cookieJar();`
then
`HttpUrl httpUrl = HttpUrl.parse(yourUrl);`
and create `List<Cookie>` with Cookie.Builder
`realmCookieJar.saveFromResponse(httpUrl, cookies);`
